server:
  port: 8082
spring:
  datasource:
   url: jdbc:mysql://localhost:3306/product-merchant-app?createDatabaseIfNotExist=true
   username: root
   password: admin
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
      formate_sql: true 
    show-sql: true       
   
        
      
        